<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-5DBSC07H" failures="0" tests="7" name="dependanceongroups.DependanceOnGroupsTest" time="0.018" errors="1" timestamp="2022-08-25T18:30:24 IST" skipped="4">
  <testcase classname="dependanceongroups.DependanceOnGroupsTest" name="test5" time="0.000">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="dependanceongroups.DependanceOnGroupsTest" name="test1" time="0.008"/>
  <system-out/>
  <testcase classname="dependanceongroups.DependanceOnGroupsTest" name="test3" time="0.003">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at dependanceongroups.DependanceOnGroupsTest.test3(DependanceOnGroupsTest.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="dependanceongroups.DependanceOnGroupsTest" name="test6" time="0.000">
    <skipped/>
  </testcase> <!-- test6 -->
  <system-out/>
  <testcase classname="dependanceongroups.DependanceOnGroupsTest" name="test7" time="0.000">
    <skipped/>
  </testcase> <!-- test7 -->
  <system-out/>
  <testcase classname="dependanceongroups.DependanceOnGroupsTest" name="test4" time="0.005">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase classname="dependanceongroups.DependanceOnGroupsTest" name="test2" time="0.002"/>
  <system-out/>
</testsuite> <!-- dependanceongroups.DependanceOnGroupsTest -->
